name: ultimate_gym_app
description: Ultimate Gym mobile app - dashboard for Members, Trainers, and Owners.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  google_fonts: ^6.2.1
  fl_chart: ^0.69.0
  cached_network_image: ^3.3.1
  url_launcher: ^6.3.2
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/UG_Logo.png
